CREATE DATABASE social_media;
USE social_media;
--
CREATE TABLE IF NOT EXISTS Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Bio TEXT,
  ProfilePicture VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--
CREATE TABLE IF NOT EXISTS Posts (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Content TEXT,
  ImageURL VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);
--
CREATE TABLE IF NOT EXISTS Comments (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PostID INT NOT NULL,
  UserID INT NOT NULL,
  Text TEXT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PostID) REFERENCES Posts(ID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);
--
CREATE TABLE IF NOT EXISTS Likes (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PostID INT NOT NULL,
  UserID INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PostID) REFERENCES Posts(ID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE,
  UNIQUE (PostID, UserID)
);
--
CREATE TABLE IF NOT EXISTS Followers (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FollowerID INT NOT NULL,
  FollowingID INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (FollowerID) REFERENCES Users(ID) ON DELETE CASCADE,
  FOREIGN KEY (FollowingID) REFERENCES Users(ID) ON DELETE CASCADE,
  UNIQUE (FollowerID, FollowingID)
);
--
CREATE TABLE IF NOT EXISTS Notifications (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ReceiverID INT NOT NULL,
  SenderID INT,
  Type ENUM('like', 'comment', 'follow') NOT NULL,
  PostID INT,
  IsRead BOOLEAN DEFAULT FALSE,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ReceiverID) REFERENCES Users(ID) ON DELETE CASCADE,
  FOREIGN KEY (SenderID) REFERENCES Users(ID) ON DELETE SET NULL,
  FOREIGN KEY (PostID) REFERENCES Posts(ID) ON DELETE CASCADE
);
--
CREATE TABLE IF NOT EXISTS Messages (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SenderID INT NOT NULL,
  ReceiverID INT NOT NULL,
  Content TEXT NOT NULL,
  Seen BOOLEAN DEFAULT FALSE,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (SenderID) REFERENCES Users(ID) ON DELETE CASCADE,
  FOREIGN KEY (ReceiverID) REFERENCES Users(ID) ON DELETE CASCADE,
  INDEX idx_sender_receiver (SenderID, ReceiverID),
  INDEX idx_receiver_sender (ReceiverID, SenderID)
);